### ISSUE TITLE
Possibility to disable propagation on form submission

### ISSUE THREAD

**Issue by burzaszsolt** [knightburton/react-use-form#5]
In most cases I don't want a nested form to propagate the submit event to a parent form.

I would like to have an option at initialization to disable the propagation.

**Comment by knightburton** [comment]
@burzaszsolt Hi
Thanks for the request, nice one. This will be available in the next release, `v1.2.0`

**Comment by knightburton** [comment]
@burzaszsolt This is feature request is fulfilled, the new release is available. I close this issue.
